### ISSUE TITLE
Mention list not updating as text changes

### ISSUE THREAD

**Issue by mrafayfarooq** [omar14/OEMentions#4]
**Describe the bug**
When the user starts the mention using "@" the list of entities appears but if you type "@ab" then instead of filtering the mention list with only those id, name starting with ab the list doesn't change

**To Reproduce**
1. Download the sample app
2. Write "@" and the list of names will appear
3. Write "@cat" and the list will not update

**Expected behavior**
The list should filter as user types

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shoaibhussan15** [comment]
@mrafayfarooq  any update on this
have you added filtration functionality?

**Comment by mrafayfarooq** [comment]
@shoaibhussan15 yes, I added the functionality my self.

**Comment by omar14** [comment]
Hi @mrafayfarooq 

I couldn't reproduce the issue as it is always filtering the name, can you try the [latest release](https://github.com/omar14/OEMentions/releases/tag/0.1.3) or update the pod and let me know if the issue still exist.

**Comment by shoaibhussan15** [comment]
@omar14  app crashes on simulator iPhone XS Max with latest release as soon I press @ sign.

**Comment by omar14** [comment]
@shoaibhussan15 It shouldn't happen, but make sure you're using the simulator keyboard (command + K to toggle) not the laptop.

**Comment by mrafayfarooq** [comment]
> @omar14 app crashes on simulator iPhone XS Max with latest release as soon I press @ sign.

yes, if you are not using the virtual keyboard it will crash since the views are expecting to have a keyboard view when presenting the table

**Comment by omar14** [comment]
The issue should be fixed in the latest release so I'm going to close it
