### ISSUE TITLE
not working on 2nd or 3rd line untill we add space.

### ISSUE THREAD

**Issue by shoaibhussan15** [omar14/OEMentions#5]
it is not showing any suggestion in 2nd or 3rd line of textview?

**Comment by omar14** [comment]
Thanks @shoaibhussan15 

It is fixed in the latest release 👍

**Comment by shoaibhussan15** [comment]
Thank you @omar14  for the solution.
can you please add another delegate method that informs us whenever a mention is deleted?
as we need to update the filtered list and add it back again in suggestion list.
