### ISSUE TITLE
Problems with Dark mode

### ISSUE THREAD

**Issue by kelvinperea** [omar14/OEMentions#8]
Hello! The problem we are having with the library is that when you select one of the users, all the text that was already written in the textView is changed to black. So for the dark mode, it becomes impossible to read.

No matter what color you indicate in this line of code, it is always modified to black once a tableView option is selected.
![image](https://user-images.githubusercontent.com/52806593/69249845-331ef480-0b74-11ea-8acc-3bcd0ed82a73.png)

This is what happens:
![WhatsApp Image 2019-11-19 at 6 20 46 PM](https://user-images.githubusercontent.com/52806593/69250055-96a92200-0b74-11ea-8eba-e22452b363d7.jpeg)

As you can see the text before the mention is in black
![WhatsApp Image 2019-11-19 at 6 20 46 PM (1)](https://user-images.githubusercontent.com/52806593/69250107-b04a6980-0b74-11ea-9bbb-13fe2d397dfc.jpeg)

What we are trying to achieve is that the text that is not a mention is displayed in system label format after selecting a user to be seen in both modes of iOS 13.

**Comment by omar14** [comment]
Hi @Kelvinjose33 

Thanks for reporting the issue, and its now fixes in the latest release [0.1.4](https://github.com/omar14/OEMentions/releases/tag/0.1.4).

Also just FYI, you can always change the color of the mentions or the text using the variables `` nameColor `` and ``notMentionColor`` of the OEMentions object.
